export const GALLERY_UPDATE_REQUEST: "GALLERY_UPDATE_REQUEST" =
  "GALLERY_UPDATE_REQUEST";
export const GALLERY_UPDATE_REQUEST_SUCCESS: "GALLERY_UPDATE_REQUEST_SUCCESS" =
  "GALLERY_UPDATE_REQUEST_SUCCESS";
export const GALLERY_UPDATE_REQUEST_FAIL: "GALLERY_UPDATE_REQUEST_FAIL" =
  "GALLERY_UPDATE_REQUEST_FAIL";
